; PlatformIO Project Configuration File

[common]
monitor_speed = 115200  ; 921600, 512000, 460800, 256000, 115200

build_flags =
    -D CONFIG_ESP_HOSTED_IDF_SLAVE_TARGET='"esp32c6"'
    -D CORE_DEBUG_LEVEL=3                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1          ; Events Run On Core
    -D BOARD_HAS_PSRAM=1
    -D MONITOR_SPEED=${this.monitor_speed}
    -Wall
    -Wextra
    -Wno-cpp                                 ; Disable #warning directive warnings
    -Wno-format                              ; Disable all format string warnings
    -Wno-unused-function
    -Wno-missing-field-initializers
    -fdiagnostics-color=always
    -Wno-error=class-memaccess

;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[env:hosted]

; Arduino 3.3.7 IDF 5.5.2
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip

board_build.partitions = boards/dev-hosted.csv
board = ESP32-P4-DevKitC-1-NRW32
board_build.filesystem = littlefs

build_flags     = ${common.build_flags}
monitor_speed   = ${common.monitor_speed}
monitor_filters = esp32_exception_decoder, send_on_enter
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

framework = arduino

custom_component_remove =
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera

;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
